'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Connect.Modules.UserManagement.AccountUpdate

    Partial Public Class Settings

        '''<summary>
        '''lblUsernameMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUsernameMode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpUsernameMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpUsernameMode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblDisplaynameMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisplaynameMode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpDisplaynameMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpDisplaynameMode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblRedirectAfterSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRedirectAfterSubmit As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpRedirectAfterSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpRedirectAfterSubmit As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblUsermanagementTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUsermanagementTab As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpUserManagementTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpUserManagementTab As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblAddToRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAddToRole As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpAddToRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpAddToRole As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblRemoveFromRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRemoveFromRole As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpRemoveFromRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpRemoveFromRole As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblNotifyRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotifyRole As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpNotifyRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpNotifyRole As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblNotifyUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotifyUser As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkNotifyUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNotifyUser As Global.System.Web.UI.WebControls.CheckBox
    End Class
End Namespace
