'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Connect.Modules.UserManagement.AccountUpdate

    Partial Public Class Templates

        '''<summary>
        '''plTheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTheme As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpThemes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpThemes As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdCopySelected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCopySelected As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDeleteSelected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDeleteSelected As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlLocales control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlLocales As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plLocale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLocale As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpLocales control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpLocales As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plUseTheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUseTheme As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkUseTheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUseTheme As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''pnlTemplateName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTemplateName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plTemplateName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTemplateName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTemplateName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTemplateName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''AccountUpdateTemplatesTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AccountUpdateTemplatesTabs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblFormTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormTemplate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmailUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailUser As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmailAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailAdmin As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFormTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFormTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEmailUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailUser As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEmailAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailAdmin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdUpdateSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdateSettings As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
